-- Migration: Remove health_survey_response table and related columns
-- Generated by health-survey removal plan

-- 1. Drop FK constraint from ai_recommendation table
ALTER TABLE ai_recommendation DROP CONSTRAINT IF EXISTS ai_recommendation_survey_response_id_health_survey_response_id_fk;

-- 2. Drop survey_response_id column from ai_recommendation
ALTER TABLE ai_recommendation DROP COLUMN IF EXISTS survey_response_id;

-- 3. Drop FK constraint from client table
ALTER TABLE client DROP CONSTRAINT IF EXISTS client_health_survey_id_health_survey_response_id_fk;

-- 4. Drop health_survey_id index from client table (if exists)
DROP INDEX IF EXISTS client_health_survey_id_idx;

-- 5. Drop health_survey_id column from client table (keep column but nullable)
-- The column is kept as nullable for migration compatibility, but not populated
ALTER TABLE client ALTER COLUMN health_survey_id DROP NOT NULL;

-- 6. Drop health_survey_response table (this also removes CASCADE dependencies)
DROP TABLE IF EXISTS health_survey_response CASCADE;

-- 7. Drop orphaned indexes from health_survey_response
DROP INDEX IF EXISTS health_survey_profile_id_idx;
DROP INDEX IF EXISTS health_survey_created_at_idx;
DROP INDEX IF EXISTS health_survey_visitor_phone_idx;
DROP INDEX IF EXISTS health_survey_visitor_whatsapp_idx;
DROP INDEX IF EXISTS ai_recommendation_survey_id_idx;

-- 8. Drop ai_recommendation_survey_id_idx if it exists separately
DROP INDEX IF EXISTS ai_recommendation_survey_id_idx;

-- Verification query (run separately):
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name LIKE '%health%';
